apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-wx2z
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-wx2z
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-wx2z
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-wx2z
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-wx2z
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-efaz-tenant/rhtap-demo-app/hacbs-test-project-wx2z@sha256:5bfc168910d83261992b99e93ab0e83a740302534cd163c14c43bd5f02a8e674
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
