apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-wx2z
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-efaz-tenant/rhtap-demo-app/hacbs-test-project-wx2z@sha256:5bfc168910d83261992b99e93ab0e83a740302534cd163c14c43bd5f02a8e674
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
